#!/usr/bin/env python

import sys
import os
from argparser import ArgParser
from commands import Commands

def main(orig_args):
	parser = ArgParser(usage="%s <command> [options]" % "mgit", version="%s 0.1" % "mgit")
	cmd, args = parser.parse(orig_args)
	cmd = Commands(cmd)
	cmd.run(args)
	
	return


if __name__ == "__main__":
	main(sys.argv)
